language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libprotobuf-dev 
      - protobuf-compiler 


before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sh compile.sh
  - sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh

script:
  - qmake -r
  - make
  - make check

notifications:
  email: true